# Generated by Django 5.1.7 on 2025-03-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerimage',
            old_name='product',
            new_name='flower',
        ),
        migrations.AlterField(
            model_name='flowerimage',
            name='image',
            field=models.ImageField(upload_to='flowers/images/'),
        ),
    ]
